backend:
  name: github
  repo: ludvigweingarten/xyz2  # Replace with your GitHub username and repository name
  branch: main  # Replace with the branch you're using (e.g., 'main', 'master')

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
